### ISSUE TITLE
Telling rails to include .js files

### ISSUE THREAD

**Issue by michaelcueno** [timothyhinrichs/rsbc#2]
Right now, birthdates_helper.rb creates a new .js file for each validation method that is run on the model. That is fine, but we need to tell rails to include these files in the application. 

I think its done with the //=file_name.js line in the applicaiton.js manifest file. So this needs to be done dynamically. 

Also I wanted to try out github's issues interface lol.

**Comment by ynnadrules** [comment]
lol. http://stackoverflow.com/questions/8448838/how-can-i-dynamically-require-assets-in-the-rails-3-1-asset-pipeline might help

**Comment by ghost** [comment]
Another option would be to generate the KIF for all of the validators and then give them all to Plato at once.  Then there would just be 1 .js file.

**Comment by michaelcueno** [comment]
Oh cool, that would be cleaner. Yeah, I'll work on that.

**Comment by ynnadrules** [comment]
i like tim's idea +1
